#!/usr/bin/env sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Custom keyboard hacks.
[ -f "${HOME}/.Xmodmap" ] && xmodmap "${HOME}/.Xmodmap"
xcape -e 'Shift_L=parenleft;Shift_R=parenright;Caps_Lock=Escape'

# Configure mouse and keyboard sensivity, disable beeping.
xset r rate 270 55
xset m 2 60
xset b off
# Fonts path.
xset +fp /usr/share/fonts/local

# Load my X defaults.
xrdb -merge "${HOME}/.Xdefaults"

# Set cursor and wallpaper for the root window.
xsetroot -cursor_name left_ptr &
[ -f "${HOME}/.fehbg" ] && eval $(cat ~/.fehbg) &

# GTK and QT settings.
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export GTK2_RC_FILES="${HOME}/.config/gtk-2.0/gtkrc"

# X apps settings.
export RXVT_SOCKET="$HOME/.cache/urxvtd.sock"
export PENTADACTYL_RUNTIME="$HOME/.config/pentadactyl"
export VIMPERATOR_RUNTIME="$HOME/.config/vimperator"
export VIMPERATOR_INIT=":source $HOME/.config/vimperator/vimperatorrc"
export GIMP2_DIRECTORY="$HOME/.config/gimp"

# Source local settings before running window manager.
[ -f "${HOME}/.local/xinitrc" ] && . "${HOME}/.local/xinitrc"

# Start window manager.
if [ -n "$2"  ] ; then wm="$2";   fi
if [ -z "$wm" ] ; then wm=xmonad; fi
exec "$wm"
