#!/usr/bin/env sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Custom keyboard hacks.
[ -f "${HOME}/.Xmodmap" ] && xmodmap "${HOME}/.Xmodmap"

# Configure mouse and keyboard sensivity.
xset r rate 270 55
xset m 2 60
# Disable beep.
xset b off

# Load my X defaults.
xrdb -merge "${HOME}/.Xdefaults"
#xrdb -DSOLARIZED_LIGHT -merge "${HOME}/.Xdefaults"

# Make GTK and QT apps use of Compose key.
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
# Themes and stuff.
export GTK2_RC_FILES="${HOME}/.gtkrc-2.0"
export OOO_FORCE_DESKTOP=gnome

# Set cursor and wallpaper for the root window.
xsetroot -cursor_name left_ptr &
[ -f "${HOME}/.fehbg" ] && eval $(cat ~/.fehbg) &


check_process() {
    if [ -x "`which $1 2>/dev/null`" -a -z "`pidof $1`" ]; then
        return 0
    else
        return 1
    fi
}

# Startup apps.
check_process urxvtd       && urxvtd -q -o -f
check_process xautolock && xautolock &

# Source local settings before running window manager.
[ -f "${HOME}/.local/xinitrc" ] && . "${HOME}/.local/xinitrc"

# Start window manager.
if [ -n "$1"  ] ; then wm="$1";   fi
if [ -z "$wm" ] ; then wm=xmonad; fi
exec "$wm"
