source /etc/X11/xinit/xinitrc.d/*

# Custom keyboard hacks.
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

# Configure mouse and keyboard sensivity.
xset r rate 270 55
xset m 2 60
# Disable beep.
xset b off


# Make GTK and QT apps use of Compose key.
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
# Themes and stuff
export GTK2_RC_FILES="$HOME/.gtkrc-2.0:$HOME/.gtkrc-2.0.mine"
export OOO_FORCE_DESKTOP=gnome

# Set cursor for the root window.
xsetroot -cursor_name left_ptr
# Set wallpaper.
[ -f ~/.fehbg ] && eval `cat ~/.fehbg` &


check_process() {
    if [ -x "`which $1 2>/dev/null`" -a -z "`pidof $1`" ]; then
        return 0
    else
        return 1
    fi
}

# Startup apps.
check_process xscreensaver && xscreensaver -no-splash &
check_process urxvtd && urxvtd -q -o -f
# Delete mpd pidfile if crashed
if [ -f ~/.mpd/pid ]; then
    pid=`cat ~/.mpd/pid`
    kill -0 $pid > /dev/null 2>&1 || rm ~/.mpd/pid
fi
# Start it up
if [ ! -f ~/.mpd/pid ]; then
    #pause=yes
    [ -n "$pause" ] && \
        cat ~/.mpd/state | sed "s/state: play/state: pause/" > ~/.mpd/state
    mpd ~/.config/mpd/config
fi

check_process stalonetray && stalonetray &
check_process fbxkb && ( sleep 3s && fbxkb ) &
check_process workrave && workrave &
# check_process unclutter && unclutter -display :0.0 -root -noevents -visible -idle 2 &
# check_process keepassx && keepassx -min -lock &
# [ -f "${HOME}/bin/dropbox.py" -a -z "`pidof dropbox`" ] && \
#     python2 $HOME/bin/dropbox.py start &

# Source local settings before running window manager.
[ -f "${HOME}/.xinitrc.local" ] && source $HOME/.xinitrc.local

# Start window manager.
if [ -n "$1" ] ; then
    wm=$1
fi
if [ -z "$wm" ] ; then
    wm=xmonad
fi
exec $wm
